# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
  - name: fastapi-service
    url: http://fastapi:8000
    routes:
      - name: fastapi-route
        paths:
          - /
